blank_issues_enabled: false
contact_links:
  - name: Preguntas de implementación
    url: https://github.com/rodrigomontenegro/prueba-tecnica-tgcorp-ci-cd/discussions
    about: Usa Discussions para dudas generales.
